### ISSUE TITLE
category and tag don't show up 

### ISSUE THREAD

**Issue by pharrellyhy** [yous/whiteglass#18]
It works fine in local but doesn't work after committed to github.

**Comment by yous** [comment]
Hi, it's because whiteglass is using [jekyll-archives](https://github.com/jekyll/jekyll-archives) gem for categories and tags archive, but GitHub Pages [doesn't support it](https://pages.github.com/versions/). I've been used Travis CI to build it, and if you want to know how to do it, see #13.

It's a bother to configure Travis CI to push site contents, so I'm considering removing jekyll-archives gem dependency and add similar features with our own source. Here's some examples:

- https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/
- https://blog.webjeda.com/jekyll-categories/

**Comment by pharrellyhy** [comment]
Thanks, Chayoung! I will take a look at it.

**Comment by hussaintamboli** [comment]
It didn't work on local for me. I followed "Quick start".

**Comment by yous** [comment]
Hi @hussaintamboli, can you show me your `_config.yml`?

**Comment by hussaintamboli** [comment]
_config.yml

```
title: For Stack, that never gets Full
author: Hussain Tamboli
theme: jekyll-whiteglass
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

google_analytics: MyGA
comments: true
```
