### ISSUE TITLE
Question: Posts with future dates

### ISSUE THREAD

**Issue by minac** [yous/whiteglass#6]
Is it possible to have posts with future dates that will only appear once the date has passed?

**Comment by yous** [comment]
Hi, you can select some posts not to be published using [`published` variable](http://jekyllrb.com/docs/frontmatter/):

``` yml
---
layout: post
date: 2017-03-30
published: false
---
```

But when a post should be published as time passes, I think you should then regenerate the site after removing `published: false` line from that post.
